services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: reviturnos
      POSTGRES_PASSWORD: reviturnos
      POSTGRES_DB: reviturnos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
